### ISSUE TITLE
e2e job should be using latest helm CLI

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-e2e#117]
The [0.4.0 version](https://ci.deis.io/job/deis-v2-e2e/1029/console) is out of date:
```
Downloading helm-0.4.0+1689ee4-linux-amd64.zip from Bintray...
```

(I know this isn't strictly in the workflow-e2e code, but this seems like the best place to enter general CI job issues.)

**Comment by sgoings** [comment]
This problem was due to the fact that we hadn't built off master since cutting helm 0.5.0 (bintray: helm repo) and ci grabs helm from the bintray helm-ci repo.

Shall we use this issue to move ci to grab helm from the bintray helm release repo instead of the latest and greatest ci version? I figure that makes sense now that helm development has stabilized a bit.

**Comment by mboersma** [comment]
> grab helm from the bintray helm release repo instead

That should work now that classic `helm` has settled down.

**Comment by smothiki** [comment]
@mboersma can we close this issue ?
