### ISSUE TITLE
Proposal: Move workflow-e2e tests to using the SDK instead of the CLI

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow-e2e#132]
To help drive stability and speed within the workflow-e2e tests we should move these tests to be driven through the SDK. This means we can explicitly check on http responses instead of waiting for buffered returns with the CLI. 

The SDK workflow-e2e tests would be the more comprehensive test suite and may include edge cases and failure modes.

The CLI workflow tests would validate the appropriate responses for all CLI actions but would not test the system as a comprehensive unit (for example we would try and stay away from exhaustive scaling of apps within the CLI test suite).

**Comment by Joshua-Anderson** [comment]
Would the cli tests still be run against a real controller backend or a mock controller backend to just test output?

**Comment by jchauncey** [comment]
Would a real controller

**Comment by arschles** [comment]
@Joshua-Anderson to add a bit more color - many of us talked internally about [refactoring these tests to run in parallel](https://github.com/deis/workflow-e2e/pull/135) (@jchauncey is doing the work there) and this issue is one of the action items that came out of that discussion.

I don't think we'll do everything at once, instead moving small pieces at a time over to the SDK.

**Comment by arschles** [comment]
Related: https://github.com/deis/workflow-cli/issues/31

**Comment by jchauncey** [comment]
Closing this issue for now.
